{% set version = "2023-8.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-optimx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/optimx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/optimx/optimx_{{ version }}.tar.gz
  sha256: 163956791eb3b09f6a9a1c8e2ccb7f44fe8e02124fc2a732701be9070a818803

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-nloptr
    - r-numderiv
    - r-pracma
  run:
    - r-base
    - r-nloptr
    - r-numderiv
    - r-pracma

test:
  commands:
    - $R -e "library('optimx')"           # [not win]
    - "\"%R%\" -e \"library('optimx')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=optimx
  license: GPL-2.0-only
  summary: Provides a replacement and extension of the optim() function to call to several function minimization codes in R in a single statement. These methods handle smooth, possibly box constrained functions  of several or many parameters. Note that function 'optimr()' was prepared to simplify the incorporation of minimization
    codes going forward. Also implements some utility codes and some extra solvers, including safeguarded Newton methods. Many methods previously separate are now included here.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: optimx
# Version: 2018-7.10
# Date: 2018-07-10
# Title: Expanded Replacement and Extension of the 'optim' Function
# Authors@R: c( person(given = c("John", "C"), family = "Nash", role = c("aut", "cre"), email = "nashjc@uottawa.ca"), person(given = "Ravi", family = "Varadhan", role = "aut", email = "RVaradhan@jhmi.edu"), person(given = "Gabor", family = "Grothendieck", role = "ctb", email = "ggrothendieck@gmail.com") )
# Author: John C Nash [aut, cre], Ravi Varadhan [aut], Gabor Grothendieck [ctb]
# Maintainer: John C Nash <nashjc@uottawa.ca>
# Description: Provides a replacement and extension of the optim() function to call to several function minimization codes in R in a single statement. These methods handle smooth, possibly box constrained functions  of several or many parameters. Note that function 'optimr()' was prepared to simplify the incorporation of minimization codes going forward. Also implements some utility codes and some extra solvers, including safeguarded Newton methods. Many methods previously separate are now included here.
# License: GPL-2
# LazyLoad: Yes
# Imports: numDeriv
# NeedsCompilation: no
# Suggests: knitr, rmarkdown, setRNG, BB, ucminf, minqa, dfoptim, lbfgsb3, lbfgs, subplex
# VignetteBuilder: knitr
# Packaged: 2018-07-10 16:08:14 UTC; john
# Repository: CRAN
# Date/Publication: 2018-09-30 14:50:05 UTC
