travis:
  secure:
    BINSTAR_TOKEN: soFwaSswJimJDY1+krdx061X6+6W0pH6GrJlIJTzfVvvh1BjK+8n+VKsx0XuyUC+zwKLKcBrx19+RxF3a5alir/iq32r3weZ2RhkTP55Xkp1fnYWzEKW2w02YgFY0xdX6zJ8d7dIbKqk90AG9i2/dzUWq9VGT9Cp9W3LgZnKSPJzBD74giY2++It0wknI2MOrtCqnlP2yd/bJ7dwjUCrUJFJBQdDSBiCHCAb8uPpPSdvA7k33NJfXtGDOLUuvuyAI7dVxGspSH0WmrBSbuxx7Qfyju9JENV8fX3ZDvaTWcTS13XbcLvO6gN9UNoUoCXdioig53treCuUJgaMs9bpwW9VzOe3zKez0o55RERvBrM3vCBRhWZpz/X6kU+QmZC5SUgt+bKZMEXMzYeM91xUZXAaBTR+LyxNwJbS8on++JUIXlWGbQB5PWv9dQO6Krlixt3YlD9IJULe67P+mKBSMlbfc1WXQKR9yed3h3DQ32fXk3C7MTVKZjwBcDWxVTiKRLjR90lME1BQ39Tc32rVwX+a4lz1bM5XYRBIUcCrfnfGWjp/LfwD8oY/iDSBYX6wdtYUpORdgKXwjxcseBFqqoap2c1Mxl+HBYNDQwd/zHgv7dpVBXDHT3r+2s+xM7KJMeYeIK12wecjQvvYMW1K3vKJPJGCbQchziIHaptCOic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
