travis:
  secure:
    BINSTAR_TOKEN: AlUlNmglWl3VDBemECpwMmFd+ySIUYLajFza4a8CEunag3XXtsYe4SwuGLMbYiLyQXQEirJxsOVdtUoJXyCW+Y5F5OEPJ2nu4pNLOiCH428cVATBAIvOr7bbJ/WsQVynjGm7Hd7aJRDgUcq1fY83BnwDruD9MYzCGxYQKk4RdyTSFlJURekuY3ApAbioxpNnySAthMwUGiI3DZ9DdPmHcSAKt4nrHrWUJUNdbLYL2NypSOLzfC59h3IcBxozvBQAGxdACt1wA6kshGApdu6F2FOGAG5/4fAE9BhvgMnUqsEDvehZjFlLMioxKDEIFvtcp353BCT3K4AeVTh9EnXMG4jwo1oprPV8A59PwTBF9XWt3tVOOCFnB0lIKMDrpAzmxfwhJRpEvHbZeLshN19Y4R/O8HOk/casC2ODJCM3NyQ53OcH72HkIj8cLo6MQS0ERN99+6Q+6cWEMU/wSYJcZFH0VqRKO3xRp2JW8WKwxMUx3wHtbXZJ/YF0HQFjMzIgWSdwtgUQuKhedlo+0n2K/hqGzLze5tbQ5kHlNwVsvL+Nev2C34npa7bwRQf/NfN5rZvZG2OLG5xveLYhwAzXSd2ylTHodZy6S4MJmPwSZOqutWiVXBIOEZoKOYXZfa6arlTZYdrGgN+7rOoYdYdnBsngyfxZVPDM0F0/UaU6+S4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
